import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';

// Simple README extraction helpers
function extractFromReadme(readme: string) {
	const lines = readme.split('\n');
	const result = { who: '', what: '', why: '', where: '', when: '', how: '' };

	// Extract title/what
	const titleMatch = readme.match(/^#\s+(.+)/m);
	if (titleMatch) result.what = titleMatch[1];

	// Look for purpose/why patterns
	const whyPatterns = [/purpose:?\s*(.+)/i, /why:?\s*(.+)/i, /mission:?\s*(.+)/i];
	for (const pattern of whyPatterns) {
		const match = readme.match(pattern);
		if (match) { result.why = match[1]; break; }
	}

	// Look for installation/how patterns
	const howPatterns = [/## Installation/i, /## Getting Started/i, /## Usage/i];
	for (const pattern of howPatterns) {
		if (pattern.test(readme)) {
			result.how = 'See README for installation and usage';
			break;
		}
	}

	return result;
}

function generateProjectFaf(owner: string, repo: string, description: string, readme: string, packageJson?: any) {
	const extracted = extractFromReadme(readme);
	const timestamp = new Date().toISOString();

	// Detect stack from package.json
	let stack = 'Unknown';
	if (packageJson?.dependencies) {
		if (packageJson.dependencies.react) stack = 'React';
		else if (packageJson.dependencies.vue) stack = 'Vue';
		else if (packageJson.dependencies.svelte) stack = 'Svelte';
		else if (packageJson.dependencies.express) stack = 'Express';
		else if (packageJson.dependencies.next) stack = 'Next.js';
		else stack = 'Node.js';
	}

	return `# project.faf - AI Context Format
# Generated by builder.faf.one
# Learn more: https://faf.one

project:
  name: ${repo}
  version: ${packageJson?.version || '0.0.0'}
  created: ${timestamp}

repository:
  owner: ${owner}
  repo: ${repo}
  url: https://github.com/${owner}/${repo}

context:
  who: ${extracted.who || `${owner} team`}
  what: ${extracted.what || description || repo}
  why: ${extracted.why || 'AI context initialization via builder.faf.one'}
  where: ${extracted.where || 'GitHub'}
  when: ${extracted.when || `Initialized ${new Date().toISOString().split('T')[0]}`}
  how: ${extracted.how || 'See README for details'}

stack:
  primary: ${stack}
  ${packageJson?.dependencies ? `dependencies: ${Object.keys(packageJson.dependencies).slice(0, 5).join(', ')}` : ''}

ai_readiness:
  score: auto
  initialized_by: builder.faf.one
  readme_extracted: ${!!readme}
`;
}

export const POST: RequestHandler = async ({ request, platform }) => {
	try {
		const GITHUB_CLIENT_ID = platform?.env?.GITHUB_CLIENT_ID;
		const GITHUB_CLIENT_SECRET = platform?.env?.GITHUB_CLIENT_SECRET;

		if (!GITHUB_CLIENT_ID || !GITHUB_CLIENT_SECRET) {
			return json(
				{ success: false, error: 'GitHub OAuth not configured on this Worker' },
				{ status: 500 }
			);
		}

		const { code, owner, repo } = await request.json();

		// Step 1: Exchange code for access token
		const tokenResponse = await fetch('https://github.com/login/oauth/access_token', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
				'Accept': 'application/json'
			},
			body: JSON.stringify({
				client_id: GITHUB_CLIENT_ID,
				client_secret: GITHUB_CLIENT_SECRET,
				code
			})
		});

		const tokenData = await tokenResponse.json();
		const accessToken = tokenData.access_token;

		if (!accessToken) {
			return json({ success: false, error: 'Failed to get access token' }, { status: 401 });
		}

		// Step 2: Fetch repo metadata
		const repoResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
			headers: {
				'Authorization': `Bearer ${accessToken}`,
				'Accept': 'application/vnd.github.v3+json'
			}
		});

		if (!repoResponse.ok) {
			return json({ success: false, error: 'Failed to fetch repo metadata' }, { status: 404 });
		}

		const repoData = await repoResponse.json();
		const description = repoData.description || '';

		// Step 3: Fetch README via GitHub API
		const readmeResponse = await fetch(
			`https://api.github.com/repos/${owner}/${repo}/readme`,
			{
				headers: {
					'Authorization': `Bearer ${accessToken}`,
					'Accept': 'application/vnd.github.v3.raw'
				}
			}
		);

		const readmeContent = readmeResponse.ok ? await readmeResponse.text() : '';

		// Step 4: Fetch package.json (if exists) for better detection
		const packageResponse = await fetch(
			`https://api.github.com/repos/${owner}/${repo}/contents/package.json`,
			{
				headers: {
					'Authorization': `Bearer ${accessToken}`,
					'Accept': 'application/vnd.github.v3.raw'
				}
			}
		);

		let packageData = null;
		if (packageResponse.ok) {
			const packageContent = await packageResponse.text();
			try {
				packageData = JSON.parse(packageContent);
			} catch (e) {
				// Invalid JSON, skip
			}
		}

		// Step 5: Generate project.faf
		const fafContent = generateProjectFaf(owner, repo, description, readmeContent, packageData);

		// Step 6: Parse score and extracted fields
		const hasWho = /who:\s*(.+)/m.test(fafContent);
		const hasWhat = /what:\s*(.+)/m.test(fafContent);
		const hasWhy = /why:\s*(.+)/m.test(fafContent);
		const hasWhere = /where:\s*(.+)/m.test(fafContent);
		const hasWhen = /when:\s*(.+)/m.test(fafContent);
		const hasHow = /how:\s*(.+)/m.test(fafContent);

		const extracted = { who: hasWho, what: hasWhat, why: hasWhy, where: hasWhere, when: hasWhen, how: hasHow };
		const missingFields = [];
		if (!hasWhy) missingFields.push('why');
		if (!hasWhen) missingFields.push('when');

		// Simple score calculation (typically 85% for init + readme)
		const filledCount = Object.values(extracted).filter(Boolean).length;
		const score = Math.round((filledCount / 6) * 100);

		// Step 7: Commit to GitHub via API
		const commitResponse = await fetch(
			`https://api.github.com/repos/${owner}/${repo}/contents/project.faf`,
			{
				method: 'PUT',
				headers: {
					'Authorization': `Bearer ${accessToken}`,
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({
					message: 'chore: Initialize project.faf (AI Context Format)',
					content: Buffer.from(fafContent).toString('base64'),
					committer: {
						name: 'FAF Builder',
						email: 'builder@faf.one'
					}
				})
			}
		);

		if (!commitResponse.ok) {
			const errorData = await commitResponse.json();
			throw new Error(`GitHub API error: ${errorData.message}`);
		}

		return json({ success: true, owner, repo, score, extracted, missingFields });
	} catch (error) {
		console.error('Error adding project.faf:', error);
		return json(
			{
				success: false,
				error: error instanceof Error ? error.message : 'Unknown error'
			},
			{ status: 500 }
		);
	}
};
